# Generated by Django 4.2.11 on 2024-11-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavepolicyrules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereason',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default=1, max_length=8),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default=1, max_length=8),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default=1, max_length=8),
        ),
    ]
