# Generated by Django 4.2.11 on 2024-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavepolicyrules', '0002_leavereason_status_leaverule_status_leavetype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereason',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
