# Generated by Django 5.1.2 on 2024-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'Hr'), ('pm', 'Pm'), ('tl', 'Tl'), ('developer', 'Developer')], default='developer'),
        ),
    ]
