# Generated by Django 5.1.2 on 2024-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'Hr'), ('pm', 'Pm'), ('tl', 'Tl'), ('developer', 'Developer')]),
        ),
    ]
