# Generated by Django 5.1.2 on 2024-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='Username'),
        ),
    ]
