# Generated by Django 5.1.2 on 2024-10-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavepolicyrules', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='requested_date',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leavepolicyrules.leavereason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_rule',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leavepolicyrules.leaverule'),
        ),
    ]
