# Generated by Django 5.1.2 on 2024-10-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavepolicyrules', '0001_initial'),
        ('policy', '0002_rename_start_date_leaverequest_requested_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavepolicyrules.leavereason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavepolicyrules.leaverule'),
        ),
    ]
