# Generated by Django 5.1.2 on 2024-10-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_remove_leavereason_name_leavetype_leaverequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereason',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.leavetype'),
        ),
    ]
