# Generated by Django 5.1.2 on 2024-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_alter_leaverequest_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
