# Generated by Django 4.2.11 on 2024-11-26 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_alter_leaverequest_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 11, 26)),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 11, 26)),
        ),
    ]
