# Generated by Django 4.2.11 on 2024-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_leaverequest_end_date_leaverequest_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
