# Generated by Django 4.2.11 on 2024-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_alter_leaverequest_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
