# Generated by Django 4.2.11 on 2024-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0010_remove_leaverequest_requested_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(),
        ),
    ]
