# Generated by Django 4.2.11 on 2024-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_alter_leaverequest_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
