# Generated by Django 4.2.11 on 2024-11-27 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0012_alter_leaverequest_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_tl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_tl', to=settings.AUTH_USER_MODEL),
        ),
    ]
