# Generated by Django 4.2.11 on 2024-11-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_remove_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
