# Generated by Django 4.2.11 on 2024-11-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
