# Generated by Django 4.2.11 on 2024-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0017_leaverequest_hr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='pm_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tl_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
