# Generated by Django 4.2.11 on 2024-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0018_leaverequest_pm_status_leaverequest_tl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='admin_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
