# Generated by Django 4.2.11 on 2024-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0019_leaverequest_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='admin_status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='hr_status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='pm_status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='tl_status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2),
        ),
    ]
