# Generated by Django 4.2.11 on 2024-11-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0020_alter_leaverequest_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
